language: node_js

node_js:
  - "11"


language: ruby
rbenv:
 - 1.1.1
 - jruby

 before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database stock-tracker_test;' -U postgres


before_install:
  - npm i -g npm@version-number

script:
  - bundle exec rails db:migrate RAILS_ENV=test

 cache:
  npm: true
  directories:
    - node_modules